<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>ExamApp.Foundation</PackageId>
    <Version>1.4.0</Version>
    <Authors>ExamApp Team</Authors>
    <Company>ExamApp</Company>
    <Description>Shared event contracts, persistence layer for OutboxMessage and EF context</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

</Project>
