apiVersion: v1
kind: ConfigMap
metadata:
  name: examapp-config
  CORS_ALLOWED_ORIGIN_0: https://exam.example.com
  namespace: examapp
data:
  PUBLIC_BASE_URL: https://exam.example.com
  KEYCLOAK_REDIRECT_URI: https://exam.example.com/app/callback
  KEYCLOAK_CLIENT_CALLBACK_URL: https://exam.example.com/app/callback&response_type=code&scope=openid&state=https://exam.example.com
  KEYCLOAK_REALM: exam-realm
  KEYCLOAK_AUTHORITY: https://exam.example.com/realms/exam-realm
  KEYCLOAK_HOST_INTERNAL: http://keycloak.examapp.svc.cluster.local:8080
  MINIO_ENDPOINT: minio.examapp.svc.cluster.local:9000
  MINIO_BASE_URL: https://exam.example.com/img
  GEMINI_MODEL: models/gemini-3.5-flash-lite
  GEMINI_CACHED_CONTENT: cachedContents/REPLACE_ME
  TZ: Europe/Istanbul
  AUTH_API_BASE_URL: http://auth-api.examapp.svc.cluster.local:5079
  EXAM_API_BASE_URL: http://exam-dotnet-api.examapp.svc.cluster.local:5079
  ASPNETCORE_ENVIRONMENT: Production
  BADGE_AI_ACTIVE: 'true'
