apiVersion: v1
kind: Secret
metadata:
  name: examapp-secrets
  namespace: examapp
type: Opaque
stringData:
  JWT_KEY: CHANGE_ME_MIN_32_CHARS

  POSTGRES_USER: examuser
  POSTGRES_PASSWORD: CHANGE_ME

  REDIS_PASSWORD: CHANGE_ME
  REDIS_CONNECTION: redis.examapp.svc.cluster.local:6379,password=CHANGE_ME
  RABBITMQ_USER: rabbituser
  RABBITMQ_PASS: CHANGE_ME

  GEMINI_API_KEY: CHANGE_ME

  MINIO_ROOT_USER: minioadmin
  MINIO_ROOT_PASSWORD: CHANGE_ME

  KEYCLOAK_CLIENT_ID: exam-client
  KEYCLOAK_CLIENT_SECRET: CHANGE_ME
  KEYCLOAK_ADMIN_CLIENT_ID: exam-admin
  KEYCLOAK_ADMIN_CLIENT_SECRET: CHANGE_ME

  CONNECTIONSTRINGS_EXAM: Host=<CLOUD_SQL_PRIVATE_IP_OR_DNS>;Port=5432;Database=worksheet_v2;Username=examuser;Password=CHANGE_ME
  CONNECTIONSTRINGS_AUTH: Host=<CLOUD_SQL_PRIVATE_IP_OR_DNS>;Port=5432;Database=auth_db;Username=examuser;Password=CHANGE_ME
  CONNECTIONSTRINGS_BADGE: Host=<CLOUD_SQL_PRIVATE_IP_OR_DNS>;Port=5432;Database=badge;Username=examuser;Password=CHANGE_ME
