apiVersion: v1
kind: Secret
metadata:
  name: examapp-secrets
  namespace: examapp
type: Opaque
stringData:
  JWT_KEY: DM7R^UEv#%SA8!_-2j*OrG3^_E!T3KL$Q3^OY6KqBIHms+4H

  POSTGRES_USER: examuser
  POSTGRES_PASSWORD: 7lMmMbP4CRzwDQqVp4PCu79E

  REDIS_PASSWORD: 8GWkb49zKEz5Ia4azkDSHJ9S
  REDIS_CONNECTION: redis.examapp.svc.cluster.local:6379,password=8GWkb49zKEz5Ia4azkDSHJ9S
  RABBITMQ_USER: rabbituser
  RABBITMQ_PASS: JHORn6lfjetDLhYEx285rWzu

  GEMINI_API_KEY: CHANGE_ME

  MINIO_ROOT_USER: minioadmin
  MINIO_ROOT_PASSWORD: 8w9wPCvBWjDTr8fzN8IHZAze

  KEYCLOAK_CLIENT_ID: exam-client
  KEYCLOAK_CLIENT_SECRET: dXqv$i&l=m*DV~6aUQ7MRKDHdOC~fechg43%5qi#
  KEYCLOAK_ADMIN_CLIENT_ID: exam-admin
  KEYCLOAK_ADMIN_CLIENT_SECRET: $c1JTYn*Kt4MeWLy5Gba4+fHEGdx@IbKXwe9VFz+
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: admin

  CONNECTIONSTRINGS_EXAM: Host=postgres.examapp.svc.cluster.local;Port=5432;Database=worksheet_v2;Username=examuser;Password=7lMmMbP4CRzwDQqVp4PCu79E
  CONNECTIONSTRINGS_AUTH: Host=postgres.examapp.svc.cluster.local;Port=5432;Database=auth_db;Username=examuser;Password=7lMmMbP4CRzwDQqVp4PCu79E
  CONNECTIONSTRINGS_BADGE: Host=postgres.examapp.svc.cluster.local;Port=5432;Database=badge;Username=examuser;Password=7lMmMbP4CRzwDQqVp4PCu79E
