// <auto-generated />
using System;
using BadgeService;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BadgeService.Migrations
{
    [DbContext(typeof(BadgeDbContext))]
    [Migration("20260906120000_AddNotificationSourceAccessRequestId")]
    partial class AddNotificationSourceAccessRequestId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BadgeService.Entities.BadgeDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IconUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PathKey")
                        .HasColumnType("text");

                    b.Property<string>("PathName")
                        .HasColumnType("text");

                    b.Property<int?>("PathOrder")
                        .HasColumnType("integer");

                    b.Property<string>("RuleConfigJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BadgeDefinitions");
                });

            modelBuilder.Entity("BadgeService.Entities.BadgeEarned", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BadgeDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EarnedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BadgeDefinitionId");

                    b.ToTable("BadgeEarned");
                });

            modelBuilder.Entity("BadgeService.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Data")
                        .HasColumnType("text");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<int?>("SourceAccessRequestId")
                        .HasColumnType("integer");

                    b.Property<int?>("SourceReminderId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("UserKeycloakId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Type", "SourceAccessRequestId")
                        .IsUnique()
                        .HasFilter("\"SourceAccessRequestId\" IS NOT NULL");

                    b.HasIndex("Type", "SourceReminderId")
                        .IsUnique()
                        .HasFilter("\"SourceReminderId\" IS NOT NULL");

                    b.HasIndex("UserId", "IsRead", "CreatedAt");

                    b.HasIndex("UserKeycloakId", "IsRead", "CreatedAt");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("BadgeService.Entities.StudentBadgeProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BadgeDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentValue")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TargetValue")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BadgeDefinitionId");

                    b.HasIndex("UserId", "BadgeDefinitionId")
                        .IsUnique();

                    b.ToTable("StudentBadgeProgresses");
                });

            modelBuilder.Entity("BadgeService.Entities.StudentDailyActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ActivityDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ActivityScore")
                        .HasColumnType("integer");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("QuestionCount")
                        .HasColumnType("integer");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("integer");

                    b.Property<int>("TotalTimeSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ActivityDate")
                        .IsUnique();

                    b.ToTable("StudentDailyActivities");
                });

            modelBuilder.Entity("BadgeService.Entities.StudentQuestionAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BestCorrectStreak")
                        .HasColumnType("integer");

                    b.Property<int>("CorrectQuestions")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentCorrectStreak")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastAnsweredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("integer");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("integer");

                    b.Property<int>("TotalTimeSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("StudentQuestionAggregates");
                });

            modelBuilder.Entity("BadgeService.Entities.StudentSubjectAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CorrectQuestions")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("integer");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("integer");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("integer");

                    b.Property<int>("TotalTimeSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "SubjectId")
                        .IsUnique();

                    b.ToTable("StudentSubjectAggregates");
                });

            modelBuilder.Entity("BadgeService.Entities.BadgeEarned", b =>
                {
                    b.HasOne("BadgeService.Entities.BadgeDefinition", "BadgeDefinition")
                        .WithMany()
                        .HasForeignKey("BadgeDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BadgeDefinition");
                });

            modelBuilder.Entity("BadgeService.Entities.StudentBadgeProgress", b =>
                {
                    b.HasOne("BadgeService.Entities.BadgeDefinition", "BadgeDefinition")
                        .WithMany()
                        .HasForeignKey("BadgeDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BadgeDefinition");
                });
#pragma warning restore 612, 618
        }
    }
}
